version: '3.8'

services:
  tests:
    build:
      context: .
      dockerfile: docker/tests/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/opt/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
  db:
    image: postgres:16.1
    volumes:
      - ./pgdata/:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  server:
    build:
      context: .
      dockerfile: docker/homework/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  pgdata: